// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdEm3j9MnAJMj2BDs5QO0Uw-cNsIOuZM',
    appId: '1:305441934480:web:1a5ba49cf8acf6868c9c15',
    messagingSenderId: '305441934480',
    projectId: 'carparkingfive-3c5a2',
    authDomain: 'carparkingfive-3c5a2.firebaseapp.com',
    storageBucket: 'carparkingfive-3c5a2.appspot.com',
    measurementId: 'G-F39QM6TYPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNs2DIK6BTmAPrGgQ4Qe8D-2uFkpFPJ0',
    appId: '1:305441934480:android:e0dbe757d2dbed3f8c9c15',
    messagingSenderId: '305441934480',
    projectId: 'carparkingfive-3c5a2',
    storageBucket: 'carparkingfive-3c5a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD212hizw_BHTaJRkGIVCWkUiB0ExmQAa8',
    appId: '1:305441934480:ios:a0bade14b9fd5f7a8c9c15',
    messagingSenderId: '305441934480',
    projectId: 'carparkingfive-3c5a2',
    storageBucket: 'carparkingfive-3c5a2.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD212hizw_BHTaJRkGIVCWkUiB0ExmQAa8',
    appId: '1:305441934480:ios:a0bade14b9fd5f7a8c9c15',
    messagingSenderId: '305441934480',
    projectId: 'carparkingfive-3c5a2',
    storageBucket: 'carparkingfive-3c5a2.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhdEm3j9MnAJMj2BDs5QO0Uw-cNsIOuZM',
    appId: '1:305441934480:web:09cae393d19753eb8c9c15',
    messagingSenderId: '305441934480',
    projectId: 'carparkingfive-3c5a2',
    authDomain: 'carparkingfive-3c5a2.firebaseapp.com',
    storageBucket: 'carparkingfive-3c5a2.appspot.com',
    measurementId: 'G-9Q66MK3Z0E',
  );
}
